name: Deploy to Vercel via Bun (no project.json commit)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        shell: bash
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Install Vercel CLI
        run: bun add -g vercel

      - name: Recreate .vercel/project.json
        run: |
          mkdir -p .vercel
          echo "{\"orgId\":\"${{ secrets.VERCEL_ORG_ID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECT_ID }}\"}" > .vercel/project.json

      - name: Deploy to Vercel (prebuilt)
        run: vercel --prebuilt --prod --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
