name: Deploy to Vercel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ secrets.VERCEL_TOKEN != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-args: --prod --yes --prebuilt --archive=tgz