name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Upstream Sync"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ secrets.BUN_VERSION }}

      - name: Restore Bun Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: bun install

      - name: Install Vercel CLI
        run: bun add vercel

      - name: Build Project with Vercel
        run: bunx vercel build --token ${{ secrets.VERCEL_TOKEN }} --prod --yes

      - name: Deploy to Vercel
        run: bunx vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --prebuilt --archive=tgz

      - name: Remove old deployments
        run: bunx vercel remove lobe-chat --token ${{ secrets.VERCEL_TOKEN }} --yes --safe
