name: Deploy to Vercel via Bun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        shell: bash
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies with Bun
        run: bun install

      - name: Build Project with Bun
        run: bun run build
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Install Vercel CLI
        run: bun add -g vercel

      - name: Deploy to Vercel (Prebuilt)
        run: vercel --prebuilt --prod --token $VERCEL_TOKEN
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
