name: Deploy to Vercel
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Upstream Sync"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ secrets.BUN_VERSION }}

      - name: Install Dependencies
        run: bun install

      - name: Install Vercel CLI
        run: bun add vercel

      - name: Build Project with Vercel
        run: bunx vercel build -t ${{ secrets.VERCEL_TOKEN }} --prod --yes

      - name: Deploy to Vercel
        run: bunx vercel deploy -t ${{ secrets.VERCEL_TOKEN }} --prod --yes --prebuilt --archive=tgz
